#!/bin/sh

SRC_DIR=$TOPDIR/build/gcc-3.4.4-2.16.1/build_mips/lib
DST_DIR=$INSTALL_ROOT/lib

mkdir -p $INSTALL_ROOT/lib

cp -f $SRC_DIR/ld-uClibc-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libcrypt-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libdl-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libgcc_s.so.1 $DST_DIR/
cp -f $SRC_DIR/libm-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libnsl-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libpthread-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libresolv-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/librt-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libuClibc-0.9.29.so $DST_DIR/
cp -f $SRC_DIR/libutil-0.9.29.so $DST_DIR/

cd $DST_DIR/
pwd

ln -sf ld-uClibc-0.9.29.so ld-uClibc.so.0
ln -sf libuClibc-0.9.29.so libc.so.0
ln -sf libcrypt-0.9.29.so libcrypt.so.0
ln -sf libdl-0.9.29.so libdl.so.0
ln -sf libgcc_s.so.1 libgcc_s.so
ln -sf libm-0.9.29.so libm.so
ln -sf libm-0.9.29.so libm.so.0
ln -sf libnsl-0.9.29.so libnsl.so
ln -sf libnsl-0.9.29.so libnsl.so.0
ln -sf libpthread-0.9.29.so libpthread.so
ln -sf libpthread-0.9.29.so libpthread.so.0
ln -sf libresolv-0.9.29.so libresolv.so
ln -sf libresolv-0.9.29.so libresolv.so.0
ln -sf librt-0.9.29.so librt.so
ln -sf librt-0.9.29.so librt.so.0
ln -sf libutil-0.9.29.so libutil.so.0

